# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabensammlung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Simpleaufgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage_text', models.CharField(max_length=600, verbose_name='Frage')),
                ('bearbeitungszeit', models.IntegerField(default=-1, verbose_name='Bearbeitungszeit (Sekunden)')),
                ('richtige_loesung', models.CharField(max_length=20, verbose_name='Richtige Loesung')),
                ('gegebene_antwort_text', models.CharField(blank=True, default='', max_length=600, verbose_name='Vom Schueler gegebene Antwort')),
                ('abweichungsprozent', models.IntegerField(default=0, verbose_name='Maximale prozentuale Abweichung von der gebenen Loesung')),
                ('sammlung', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aufgabensammlung.Aufgabensammlung')),
            ],
        ),
    ]
