# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage_text', models.CharField(max_length=600)),
                ('gegebene_antwort_text', models.CharField(default='', max_length=600)),
                ('bearbeitungszeit', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Simpleaufgabe',
            fields=[
                ('aufgabe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aufgabensammlung.Aufgabe')),
                ('richtige_loesung', models.CharField(max_length=20)),
                ('abweichungsprozent', models.IntegerField(default=0)),
            ],
            bases=('aufgabensammlung.aufgabe',),
        ),
    ]
