# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aufgabensammlung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_text', models.CharField(default='', max_length=600, verbose_name='Antworttext')),
            ],
        ),
        migrations.RemoveField(
            model_name='simpleaufgabe',
            name='gegebene_antwort_text',
        ),
        migrations.AddField(
            model_name='antwort',
            name='aufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aufgabensammlung.Simpleaufgabe'),
        ),
    ]
